language: go

go:
#  - 1.1 // QL fails to compile on lower then go1.2.
#  - 1.2 // "go get" SSL problems with go1.2.
#  - 1.2.1
#  - 1.2.2
  - 1.3.3
  - 1.4.3
  - 1.5.3

env:
  - GOARCH=amd64

install:
  - sudo apt-get install bzr
  - rm -rf $HOME/gopath/src/upper.io
  - mkdir -p $HOME/gopath/src/upper.io
  - rsync -az $TRAVIS_BUILD_DIR/ $HOME/gopath/src/github.com/ilovetravel/upperiodb/
  - export TRAVIS_BUILD_DIR=$HOME/gopath/src/github.com/ilovetravel/upperiodb
  - cd $TRAVIS_BUILD_DIR
  - go get -v github.com/cznic/ql/ql
  - go get ./...

services:
  - mongodb

before_script:
  - make -C mysql/_dumps
  - make -C postgresql/_dumps
  - make -C mongo/_dumps
  - make -C ql/_dumps
  - make -C sqlite/_dumps

script:
  - cd $HOME/gopath/src/github.com/ilovetravel/upperiodb
  - go version
  - go test -v -host 127.0.0.1
  - go test -v -host 127.0.0.1 github.com/ilovetravel/upperiodb/postgresql
  - go test -v -host 127.0.0.1 github.com/ilovetravel/upperiodb/mysql
  - go test -v -host 127.0.0.1 github.com/ilovetravel/upperiodb/mongo
  - go test -v github.com/ilovetravel/upperiodb/ql
  - go test -v github.com/ilovetravel/upperiodb/sqlite
